"""bundle and per-pass extraction

Revision ID: 0015
Revises: 0014
Create Date: 2026-04-11

Per spec §4.8. Adds bundle-aware columns to Source, PipelineRun, and
DocumentGraphExtraction; adds per-pass columns and the rollback_executed
gate to StageRun; replaces the old unique constraint with two narrower
partial unique indexes; creates v_latest_pass_attempts view.

NOTE: The actual DB constraint being dropped is named
'stage_runs_pipeline_run_id_stage_name_attempt_key' (auto-generated by
PostgreSQL from UniqueConstraint without explicit name). The SQLAlchemy
model declared name="uq_stage_run" but the constraint was created before
that declaration existed in the migration chain.

NOTE: DocumentGraphExtraction lives in schema 'ingest' (verified in
app/models/ingest.py line 310).
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0015"
down_revision = "0014"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- Source ---
    op.add_column(
        "sources",
        sa.Column("default_ontology_bundle_key", sa.String(100), nullable=True),
        schema="ingest",
    )
    op.add_column(
        "sources",
        sa.Column("default_use_case_key", sa.String(100), nullable=True),
        schema="ingest",
    )

    # --- PipelineRun ---
    op.add_column(
        "pipeline_runs",
        sa.Column("mode", sa.String(32), nullable=False, server_default="full"),
        schema="ingest",
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("ontology_bundle_key", sa.String(100), nullable=True),
        schema="ingest",
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("ontology_name", sa.String(255), nullable=True),
        schema="ingest",
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("ontology_version", sa.String(100), nullable=True),
        schema="ingest",
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("use_case_key", sa.String(100), nullable=True),
        schema="ingest",
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("extraction_profile_version", sa.String(100), nullable=True),
        schema="ingest",
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("metrics", postgresql.JSONB, nullable=True),
        schema="ingest",
    )
    op.create_check_constraint(
        "chk_pipeline_run_mode",
        "pipeline_runs",
        "mode IN ('full', 'graph_only')",
        schema="ingest",
    )

    # --- DocumentGraphExtraction (schema: ingest) ---
    op.add_column(
        "document_graph_extractions",
        sa.Column("pipeline_run_id", postgresql.UUID(as_uuid=True), nullable=True),
        schema="ingest",
    )
    op.create_foreign_key(
        "fk_dge_pipeline_run",
        "document_graph_extractions",
        "pipeline_runs",
        ["pipeline_run_id"],
        ["id"],
        source_schema="ingest",
        referent_schema="ingest",
        ondelete="SET NULL",
    )
    op.add_column(
        "document_graph_extractions",
        sa.Column("ontology_bundle_key", sa.String(100), nullable=True),
        schema="ingest",
    )
    op.add_column(
        "document_graph_extractions",
        sa.Column("ontology_name", sa.String(255), nullable=True),
        schema="ingest",
    )
    op.add_column(
        "document_graph_extractions",
        sa.Column("ontology_version", sa.String(100), nullable=True),
        schema="ingest",
    )
    op.add_column(
        "document_graph_extractions",
        sa.Column("use_case_key", sa.String(100), nullable=True),
        schema="ingest",
    )
    op.add_column(
        "document_graph_extractions",
        sa.Column("extraction_profile_version", sa.String(100), nullable=True),
        schema="ingest",
    )

    # --- StageRun: drop old unique constraint ---
    # The actual constraint name in the DB is the PostgreSQL auto-generated name
    # (the SQLAlchemy model declared name="uq_stage_run" but it was never applied
    # via a named migration — confirmed via pg_constraint query).
    op.drop_constraint(
        "stage_runs_pipeline_run_id_stage_name_attempt_key",
        "stage_runs",
        schema="ingest",
        type_="unique",
    )

    # --- StageRun: new per-pass columns ---
    op.add_column("stage_runs", sa.Column("pass_name", sa.String(64), nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("execution_status", sa.String(16), nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("yield_status", sa.String(16), nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("skip_reason", sa.String(32), nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("primary_entities_extracted", sa.Integer, nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("bridge_entities_extracted", sa.Integer, nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("relationships_extracted", sa.Integer, nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("relationships_rejected", sa.Integer, nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("salvaged", sa.Boolean, nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("schema_size_chars", sa.Integer, nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("structured_output_mode", sa.String(32), nullable=True), schema="ingest")
    op.add_column("stage_runs", sa.Column("rollback_executed", sa.Boolean, nullable=True), schema="ingest")

    # --- Indexes ---
    op.create_index(
        "uq_stage_runs_run_pass_attempt", "stage_runs",
        ["pipeline_run_id", "stage_name", "pass_name", "attempt"],
        unique=True,
        postgresql_where=sa.text("pass_name IS NOT NULL"),
        schema="ingest",
    )
    op.create_index(
        "uq_stage_runs_summary_row", "stage_runs",
        ["pipeline_run_id", "stage_name", "attempt"],
        unique=True,
        postgresql_where=sa.text(
            "pass_name IS NULL AND stage_name = 'derive_ontology_graph'"
        ),
        schema="ingest",
    )
    op.create_index(
        "ix_stage_runs_extraction_pass", "stage_runs",
        ["stage_name", "pass_name"],
        postgresql_where=sa.text("stage_name = 'derive_ontology_graph'"),
        schema="ingest",
    )
    op.create_index(
        "ix_stage_runs_execution_status", "stage_runs",
        ["execution_status"],
        postgresql_where=sa.text("execution_status IS NOT NULL"),
        schema="ingest",
    )

    # --- View: v_latest_pass_attempts (spec §4.4) ---
    op.execute(
        """
        CREATE VIEW ingest.v_latest_pass_attempts AS
        SELECT DISTINCT ON (pipeline_run_id, stage_name, pass_name)
            id, pipeline_run_id, stage_name, pass_name, attempt,
            status, execution_status, yield_status, skip_reason,
            primary_entities_extracted, bridge_entities_extracted,
            relationships_extracted, relationships_rejected, salvaged,
            schema_size_chars, structured_output_mode,
            error_message, started_at, finished_at
        FROM ingest.stage_runs
        WHERE pass_name IS NOT NULL
        ORDER BY pipeline_run_id, stage_name, pass_name, attempt DESC;
        """
    )


def downgrade() -> None:
    # Reverse order: drop view, drop indexes, drop columns, restore old constraint.
    op.execute("DROP VIEW IF EXISTS ingest.v_latest_pass_attempts")

    op.drop_index("ix_stage_runs_execution_status", table_name="stage_runs", schema="ingest")
    op.drop_index("ix_stage_runs_extraction_pass", table_name="stage_runs", schema="ingest")
    op.drop_index("uq_stage_runs_summary_row", table_name="stage_runs", schema="ingest")
    op.drop_index("uq_stage_runs_run_pass_attempt", table_name="stage_runs", schema="ingest")

    # Restore the original uniqueness constraint (using the actual DB name).
    op.create_unique_constraint(
        "stage_runs_pipeline_run_id_stage_name_attempt_key",
        "stage_runs",
        ["pipeline_run_id", "stage_name", "attempt"],
        schema="ingest",
    )

    # StageRun columns (reverse order of addition)
    op.drop_column("stage_runs", "rollback_executed", schema="ingest")
    op.drop_column("stage_runs", "structured_output_mode", schema="ingest")
    op.drop_column("stage_runs", "schema_size_chars", schema="ingest")
    op.drop_column("stage_runs", "salvaged", schema="ingest")
    op.drop_column("stage_runs", "relationships_rejected", schema="ingest")
    op.drop_column("stage_runs", "relationships_extracted", schema="ingest")
    op.drop_column("stage_runs", "bridge_entities_extracted", schema="ingest")
    op.drop_column("stage_runs", "primary_entities_extracted", schema="ingest")
    op.drop_column("stage_runs", "skip_reason", schema="ingest")
    op.drop_column("stage_runs", "yield_status", schema="ingest")
    op.drop_column("stage_runs", "execution_status", schema="ingest")
    op.drop_column("stage_runs", "pass_name", schema="ingest")

    # DocumentGraphExtraction (schema: ingest)
    op.drop_column("document_graph_extractions", "extraction_profile_version", schema="ingest")
    op.drop_column("document_graph_extractions", "use_case_key", schema="ingest")
    op.drop_column("document_graph_extractions", "ontology_version", schema="ingest")
    op.drop_column("document_graph_extractions", "ontology_name", schema="ingest")
    op.drop_column("document_graph_extractions", "ontology_bundle_key", schema="ingest")
    op.drop_constraint(
        "fk_dge_pipeline_run",
        "document_graph_extractions",
        schema="ingest",
        type_="foreignkey",
    )
    op.drop_column("document_graph_extractions", "pipeline_run_id", schema="ingest")

    # PipelineRun
    op.drop_constraint(
        "chk_pipeline_run_mode", "pipeline_runs", schema="ingest", type_="check",
    )
    op.drop_column("pipeline_runs", "metrics", schema="ingest")
    op.drop_column("pipeline_runs", "extraction_profile_version", schema="ingest")
    op.drop_column("pipeline_runs", "use_case_key", schema="ingest")
    op.drop_column("pipeline_runs", "ontology_version", schema="ingest")
    op.drop_column("pipeline_runs", "ontology_name", schema="ingest")
    op.drop_column("pipeline_runs", "ontology_bundle_key", schema="ingest")
    op.drop_column("pipeline_runs", "mode", schema="ingest")

    # Source
    op.drop_column("sources", "default_use_case_key", schema="ingest")
    op.drop_column("sources", "default_ontology_bundle_key", schema="ingest")
